/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piony.restaurant.project;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.io.IOException;
//import org.apache.pdfbox.pdmodel.PDDocument;
//import org.apache.pdfbox.pdmodel.PDPage;
//import com.itextpdf.text.Document;

/**
 *
 * @author frankkips
 */
public class Cachier extends javax.swing.JFrame {

    /**
     * Creates new form Cashier_Form
     */
    public Cachier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderfield = new javax.swing.JTextField();
        receiptbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        quantityfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        escortfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        amountfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radiochapati = new javax.swing.JRadioButton();
        radiochips = new javax.swing.JRadioButton();
        radiomchele = new javax.swing.JRadioButton();
        radiopilau = new javax.swing.JRadioButton();
        carbs = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        checkndengu = new javax.swing.JCheckBox();
        checkbeans = new javax.swing.JCheckBox();
        checkpeas = new javax.swing.JCheckBox();
        checknyama = new javax.swing.JCheckBox();
        escort = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipttextarea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        carbpricefield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Piony Restaurant");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Cashier");

        jLabel3.setText("Order No:");

        orderfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderfieldMouseClicked(evt);
            }
        });
        orderfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderfieldActionPerformed(evt);
            }
        });

        receiptbtn.setText("Generate Receipt");
        receiptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptbtnActionPerformed(evt);
            }
        });

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantity");

        jLabel6.setText("Escort");

        jLabel7.setText("Amount");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(radiochapati);
        radiochapati.setText("Chapati");

        buttonGroup1.add(radiochips);
        radiochips.setText("Chips");

        buttonGroup1.add(radiomchele);
        radiomchele.setText("Mchele");

        buttonGroup1.add(radiopilau);
        radiopilau.setText("Pilau");
        radiopilau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiopilauActionPerformed(evt);
            }
        });

        carbs.setText("Carbs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiopilau)
                            .addComponent(radiomchele)
                            .addComponent(radiochips)
                            .addComponent(radiochapati)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(carbs)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carbs)
                .addGap(10, 10, 10)
                .addComponent(radiochapati)
                .addGap(18, 18, 18)
                .addComponent(radiochips)
                .addGap(18, 18, 18)
                .addComponent(radiomchele)
                .addGap(18, 18, 18)
                .addComponent(radiopilau)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup2.add(checkndengu);
        checkndengu.setText("Ndengu");

        buttonGroup2.add(checkbeans);
        checkbeans.setText("Beans");

        buttonGroup2.add(checkpeas);
        checkpeas.setText("Peas");

        buttonGroup2.add(checknyama);
        checknyama.setText("Nyama");

        escort.setText("Escort");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checknyama)
                    .addComponent(checkpeas)
                    .addComponent(checkbeans)
                    .addComponent(checkndengu))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(escort)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escort)
                .addGap(3, 3, 3)
                .addComponent(checkndengu)
                .addGap(18, 18, 18)
                .addComponent(checkbeans)
                .addGap(18, 18, 18)
                .addComponent(checkpeas)
                .addGap(18, 18, 18)
                .addComponent(checknyama)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        receipttextarea.setColumns(20);
        receipttextarea.setRows(5);
        jScrollPane1.setViewportView(receipttextarea);

        jLabel8.setText("Carbs price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(receiptbtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearbtn))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(carbpricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(orderfield, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(40, 40, 40)
                                            .addComponent(quantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(amountfield, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(escortfield, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(orderfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(escortfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(quantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(amountfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(carbpricefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptbtn)
                    .addComponent(clearbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void receiptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptbtnActionPerformed
        // TODO add your handling code here:
        int orderNo = Integer.parseInt(orderfield.getText());
        int qty = Integer.parseInt(quantityfield.getText());
        double price = 0;
        String carbs = null;
        
        
        
        //prices
        if (radiochapati.isSelected()){
            price = 10;
            carbs = "chapati";
        }
        else if (radiochips.isSelected()){
            price = 30;
            carbs = "chips";
        }
        else if (radiomchele.isSelected()){
            price = 15;
            carbs = "mchele";
        }
        else if (radiopilau.isSelected()){
            price = 35;
            carbs = "pilau";
        }
        
        //Dispaly price 
        double carbsTotal = qty * price;
        carbpricefield.setText("" + carbsTotal);
        
        double escort = 0;
        String jina = null;
//        Escort conditions
        if (checkndengu.isSelected()){escort = 20; jina = "ndengu";}
        if (checkbeans.isSelected()){escort = 20; jina = "beans";}
        if (checkpeas.isSelected()){escort = 25; jina = "peas";}
        if (checknyama.isSelected()){escort = 70; jina = "nyama";}
        
        escortfield.setText("" + escort);
        
        
            
        
        //Total payable
        double total = carbsTotal + escort;
        amountfield.setText("" + total);
        
        //Display order details
        receipttextarea.setText("============================================\nHello your're order id is: " + orderNo + "\n " + carbs + "\t\t " + carbsTotal + "\n " + jina + "\t\t " + escort
        + "\nTotal Amount: \t\t" + total + "\n============================================");
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/piony","root","");
        
            PreparedStatement insert = con.prepareStatement("insert into orders(carbs,escort,Total)values(?,?,?)");  
            insert.setString(1, carbs);
            insert.setString(2, jina);
            insert.setDouble(3, total);
            insert.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }            
        
        
    }//GEN-LAST:event_receiptbtnActionPerformed

    private void radiopilauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiopilauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiopilauActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        carbpricefield.setText("");
        orderfield.setText("");
        quantityfield.setText("");
        amountfield.setText("");
        escortfield.setText("");
        radiochapati.setSelected(false);
        radiochips.setSelected(false);
        radiomchele.setSelected(false);
        radiopilau.setSelected(false);
        checkndengu.setSelected(false);
        checkbeans.setSelected(false);
        checkpeas.setSelected(false);
        checknyama.setSelected(false);
        receipttextarea.setText("");

    }//GEN-LAST:event_clearbtnActionPerformed

    private void orderfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderfieldActionPerformed

    }//GEN-LAST:event_orderfieldActionPerformed

    private void orderfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderfieldMouseClicked
        // TODO add your handling code here:
        try {
            // Get The orderNo and dispaly it on the Screen
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/piony","root","");
            String query = "SELECT orderNo FROM orders ORDER BY orderNo DESC LIMIT 1;";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery(query);
            
            if (rs.next()){
                int orderNum = rs.getInt("orderNo");
                int or = orderNum + 1;
                String oj = Integer.toString(or);
                orderfield.setText(oj);
            }else {
                orderfield.setText("1");
            }
            
        
        } catch (SQLException ex) {
            Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_orderfieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Cachier().setVisible(true);
//                orderNumber ();
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField carbpricefield;
    private javax.swing.JLabel carbs;
    private javax.swing.JCheckBox checkbeans;
    private javax.swing.JCheckBox checkndengu;
    private javax.swing.JCheckBox checknyama;
    private javax.swing.JCheckBox checkpeas;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel escort;
    private javax.swing.JTextField escortfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orderfield;
    private javax.swing.JTextField quantityfield;
    private javax.swing.JRadioButton radiochapati;
    private javax.swing.JRadioButton radiochips;
    private javax.swing.JRadioButton radiomchele;
    private javax.swing.JRadioButton radiopilau;
    private javax.swing.JButton receiptbtn;
    private javax.swing.JTextArea receipttextarea;
    // End of variables declaration//GEN-END:variables

}
